# Generated by Django 5.0.3 on 2024-04-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_cat_feeding_dog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeding',
            name='date',
            field=models.DateTimeField(verbose_name='Feeding Date and Time'),
        ),
    ]
